package com.service.politic13;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2022-04-17T10:29:10.048+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "PoliticUserService", 
                  wsdlLocation = "http://localhost:8080/com.service.politic13/services/PoliticUserPort?wsdl",
                  targetNamespace = "http://politic13.service.com/") 
public class PoliticUserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://politic13.service.com/", "PoliticUserService");
    public final static QName PoliticUserPort = new QName("http://politic13.service.com/", "PoliticUserPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/com.service.politic13/services/PoliticUserPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PoliticUserService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/com.service.politic13/services/PoliticUserPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PoliticUserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PoliticUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PoliticUserService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PoliticUserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PoliticUserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PoliticUserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PoliticUser
     */
    @WebEndpoint(name = "PoliticUserPort")
    public PoliticUser getPoliticUserPort() {
        return super.getPort(PoliticUserPort, PoliticUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PoliticUser
     */
    @WebEndpoint(name = "PoliticUserPort")
    public PoliticUser getPoliticUserPort(WebServiceFeature... features) {
        return super.getPort(PoliticUserPort, PoliticUser.class, features);
    }

}
