
package com.service.politic13;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Scanner;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.java.dev.jaxb.array.StringArray;

/**
 * This class was generated by Apache CXF 2.4.2 2022-04-17T10:29:09.995+02:00
 * Generated source version: 2.4.2
 * 
 */
public final class PoliticUser_PoliticUserPort_Client {

	static final Scanner scan = new Scanner(System.in); //the scanner to get the client responses

	private static final QName SERVICE_NAME = new QName("http://politic13.service.com/", "PoliticUserService");

	private PoliticUser_PoliticUserPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = PoliticUserService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		PoliticUserService ss = new PoliticUserService(wsdlURL, SERVICE_NAME);
		PoliticUser port = ss.getPoliticUserPort();

		String continu = ""; //variable to check if the client want to continue or finish

		while (!continu.equals("n")) { //while client want to continue
			System.out.println("Add a new politician");

			String politicName = "";

			politicName += scan.nextLine(); // add a politician by the terminal

			String politicExist = port.getPoliticDescription(politicName);
			while (politicExist.equals("")) { //if the politician is not in the hash map defined in the PoliticInfo class
				System.out.println("This politician is not identified ! Enter again a new politician ");
				politicName = "";
				politicName += scan.nextLine();
				politicExist = port.getPoliticDescription(politicName);
			}

			String politicAdd = port.addPolitician(politicName);

			System.out.println(politicAdd); //the politician is added to the client's list

			System.out.println("Do you want information about this politician ? (y/n) ");

			String response = scan.next();

			if (response.equals("y")) {
				String description = port.getPoliticDescription(politicName);
				System.out.println(description); //display the description about the politician added
				
				System.out.println("\nThe lasts Tweets for the political party : \n");

				List<StringArray> politicTweet = port.getTweetPolitic(politicName); //get the recents tweets of the politician's political party

				for (int i = 0; i < politicTweet.size(); i++) {
					System.out.println("Tweet date : " + politicTweet.get(i).getItem().get(0)); //display the tweet date
					System.out.println("Tweet text : " + politicTweet.get(i).getItem().get(1) + "\n"); //display the tweet text
				}
				
			
			}
			
			System.out.println("\nYour List of politicians : ");
			String politicList = port.displayPoliticList(); //the client's politician list

			System.out.println(politicList);
			
			System.out.println("\nDo you want informations again about one politician of your list ? (y/n)");
			
			String infoAgain = scan.next();
			scan.nextLine();

			while(!infoAgain.equals("n")) { //while the client want to see informations about a politician of his list
				
				System.out.println("Which one ?");

				String politicNameAgain = "";
				politicNameAgain += scan.nextLine();

				
				while(!port.politicInList(politicNameAgain)) { //check if the politician entered by the client is in his list
					System.out.println("\n This politician is not in your List ! Enter a politician of your list");
					politicNameAgain = "";
					politicNameAgain += scan.nextLine();
				}
				String descriptionAgain = port.getPoliticDescription(politicNameAgain);
				System.out.println(descriptionAgain + "\n"); //display the informations about the politician
				
				List<StringArray> politicTweetAgain = port.getTweetPolitic(politicNameAgain); //get the recents tweets of the politician's political party

				for (int i = 0; i < politicTweetAgain.size(); i++) {
					System.out.println("Tweet date : " + politicTweetAgain.get(i).getItem().get(0)); //display the tweet date
					System.out.println("Tweet text : " + politicTweetAgain.get(i).getItem().get(1) + "\n"); //display the tweet text
				}
				
				System.out.println("\nDo you want informations again about one politician of your list ? (y/n)");
				
				infoAgain = scan.next();
				scan.nextLine();
			}

			System.out.println("\nDo you want to add a new Politician ? (y/n)");
			continu = scan.next();
			scan.nextLine();
		}

		System.out.println("End of the program");
		System.exit(port.clearList()); //exit the program with the return 0 in System.exit
	}

}
