
package com.service.politic13;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Scanner;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.java.dev.jaxb.array.StringArray;

/**
 * This class was generated by Apache CXF 2.4.2 2022-04-17T10:29:09.995+02:00
 * Generated source version: 2.4.2
 * 
 */
public final class PoliticUser_PoliticUserPort_Client {

	static final Scanner scan = new Scanner(System.in);

	private static final QName SERVICE_NAME = new QName("http://politic13.service.com/", "PoliticUserService");

	private PoliticUser_PoliticUserPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = PoliticUserService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		PoliticUserService ss = new PoliticUserService(wsdlURL, SERVICE_NAME);
		PoliticUser port = ss.getPoliticUserPort();

		String continu = "";

		while (!continu.equals("n")) {
			System.out.println("Add a new politician");

			String politicName = "";

			politicName += scan.nextLine();

			String politicExist = port.getPoliticDescription(politicName);
			while (politicExist.equals("")) {
				System.out.println("This politician is not identified ! Enter again a new politician ");
				politicName = "";
				politicName += scan.nextLine();
				politicExist = port.getPoliticDescription(politicName);
			}

			String politicAdd = port.addPolitician(politicName);

			System.out.println(politicAdd);

			System.out.println("Do you want information about this politician ? (y/n) ");

			String response = scan.next();

			if (response.equals("y")) {
				String description = port.getPoliticDescription(politicName);
				System.out.println(description);
				
				System.out.println("\nThe lasts Tweets for the political party : \n");

				List<StringArray> politicTweet = port.getTweetPolitic(politicName);

				for (int i = 0; i < politicTweet.size(); i++) {
					System.out.println("Tweet date : " + politicTweet.get(i).getItem().get(0));
					System.out.println("Tweet text : " + politicTweet.get(i).getItem().get(1) + "\n");
				}
				
				
				System.out.println("\nYour List of politicians : ");
				String politicList = port.displayPoliticList();

				System.out.println(politicList);
				
				System.out.println("\nDo you want informations again about one politician of your list ? (y/n)");
				
				String infoAgain = scan.next();
				scan.nextLine();

				while(!infoAgain.equals("n")) {
					
					System.out.println("Which one ?");
	
					String politicNameAgain = "";
					politicNameAgain += scan.nextLine();
	
					/*String descriptionAgain = port.getPoliticDescription(politicNameAgain);
					System.out.println(descriptionAgain);*/
					
					while(!port.politicInList(politicNameAgain)) {
						System.out.println("\n This politician is not in your List ! Enter a politician of your list");
						politicNameAgain = "";
						politicNameAgain += scan.nextLine();
					}
					String descriptionAgain = port.getPoliticDescription(politicNameAgain);
					System.out.println(descriptionAgain);
					
					System.out.println("\nDo you want informations again about one politician of your list ? (y/n)");
					
					infoAgain = scan.next();
					scan.nextLine();
				}
			
			}

			System.out.println("\nDo you want to add a new Politician ? (y/n)");
			continu = scan.next();
			scan.nextLine();
		}

		System.exit(port.clearList());
	}

}
