
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.service.politic13;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2022-04-17T10:29:10.035+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "PoliticUserService",
                      portName = "PoliticUserPort",
                      targetNamespace = "http://politic13.service.com/",
                      wsdlLocation = "http://localhost:8080/com.service.politic13/services/PoliticUserPort?wsdl",
                      endpointInterface = "com.service.politic13.PoliticUser")
                      
public class PoliticUserImpl implements PoliticUser {

    private static final Logger LOG = Logger.getLogger(PoliticUserImpl.class.getName());

    /* (non-Javadoc)
     * @see com.service.politic13.PoliticUser#clearList(*
     */
    public int clearList() { 
        LOG.info("Executing operation clearList");
        try {
            int _return = -1574600261;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.politic13.PoliticUser#addPolitician(java.lang.String  arg0 )*
     */
    public java.lang.String addPolitician(java.lang.String arg0) { 
        LOG.info("Executing operation addPolitician");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1031877589";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.politic13.PoliticUser#displayPoliticList(*
     */
    public java.lang.String displayPoliticList() { 
        LOG.info("Executing operation displayPoliticList");
        try {
            java.lang.String _return = "_return-1516466902";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.politic13.PoliticUser#getTweetPolitic(java.lang.String  arg0 )*
     */
    public java.util.List<net.java.dev.jaxb.array.StringArray> getTweetPolitic(java.lang.String arg0) { 
        LOG.info("Executing operation getTweetPolitic");
        System.out.println(arg0);
        try {
            java.util.List<net.java.dev.jaxb.array.StringArray> _return = new java.util.ArrayList<net.java.dev.jaxb.array.StringArray>();
            net.java.dev.jaxb.array.StringArray _returnVal1 = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnVal1Item = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1ItemVal1 = "_returnVal1ItemVal29899306";
            _returnVal1Item.add(_returnVal1ItemVal1);
            _returnVal1.getItem().addAll(_returnVal1Item);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.politic13.PoliticUser#politicInList(java.lang.String  arg0 )*
     */
    public boolean politicInList(java.lang.String arg0) { 
        LOG.info("Executing operation politicInList");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.service.politic13.PoliticUser#getPoliticDescription(java.lang.String  arg0 )*
     */
    public java.lang.String getPoliticDescription(java.lang.String arg0) { 
        LOG.info("Executing operation getPoliticDescription");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return152782544";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
